[workspace]
resolver = "2"
members = [
  "crates/acyclic",
  "crates/acyclic-engine",
  "crates/acyclic-proto",
  "crates/acyclic-qual",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/acyclic-labs/graphcoder-plugin"
homepage = "https://acyclic.dev"

[workspace.dependencies]
acyclic-fs = { git = "https://github.com/acyclic-labs/sdk.git", rev = "8eced489729235929b769e831c1170c85aa1f7ba", features = ["local", "native-watch", "native-mount"] }
tokio = { version = "1.48", features = ["rt-multi-thread", "macros"] }

